### ISSUE TITLE
API v1 no longer works

### ISSUE THREAD

**Issue by chatziko** [ldx/DBdownload#11]
Since June 2017 the old API v1 is switched off, which seems to have broken DBdownload.

The only way forward is to use the v2 API.

**Comment by ldx** [comment]
Thanks for the heads up. This project has been in maintenance mode - if someone is willing to do the necessary changes to make it work with the v2 API I'll be happy to review it; otherwise, it's unclear when I'll have the time to look into it.

**Comment by coandco** [comment]
DBdownload now works with the v2 Dropbox API.
