### ISSUE TITLE
When syncing from root, need to rewrite path

### ISSUE THREAD

**Issue by lhoward** [ldx/DBdownload#14]
When syncing the entire Dropbox by specifying the source path as a single "/", the path passed to the Dropbox client library needs to be rewritten as the empty string to work.

**Comment by coandco** [comment]
Pull request merged.  Thanks for the code!

**Comment by lhoward** [comment]
Not sure if this is working correctly. After synchronising, DBdownload trashed everything and then started resynchronising (managed to stop it before it chewed up even more bandwidth). Am investigating further.
