### ISSUE TITLE
One-way local to dropbox?

### ISSUE THREAD

**Issue by ekerstein** [ldx/DBdownload#19]
Can this app do one-way synchronizing from a local directory to Dropbox? I want my local directory to be the master, and the Dropbox to be updated with any changes.

The readme makes it sound like it only does the other way (Dropbox to local), but I'm really hoping it can be configured either way. I've been having trouble finding a good client to do that.

**Comment by ldx** [comment]
Unfortunately no, this only works in the other direction (Dropbox -> local).
