### ISSUE TITLE
Error on execute

### ISSUE THREAD

**Issue by luftaquila** [ldx/DBdownload#21]
Hi, I'm using raspbian on raspberry pi 3b+.
When I tried to install and execute dbdownload, it always prints this error:

pi@luftaquila:~/DBdownload $ dbdownload --help
Traceback (most recent call last):
  File "/usr/local/bin/dbdownload", line 11, in <module>
    load_entry_point('dbdownload==0.3', 'console_scripts', 'dbdownload')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/site-packages/dbdownload-0.3-py3.7.egg/dbdownload/__init__.py", line 3, in <module>
NameError: name 'VERSION' is not defined

And here's log of sudo python3 setup.py install :

pi@luftaquila:~/DBdownload $ sudo python3 setup.py install
running install
running bdist_egg
running egg_info
creating dbdownload.egg-info
writing dbdownload.egg-info/PKG-INFO
writing dependency_links to dbdownload.egg-info/dependency_links.txt
writing entry points to dbdownload.egg-info/entry_points.txt
writing requirements to dbdownload.egg-info/requires.txt
writing top-level names to dbdownload.egg-info/top_level.txt
writing manifest file 'dbdownload.egg-info/SOURCES.txt'
reading manifest file 'dbdownload.egg-info/SOURCES.txt'
writing manifest file 'dbdownload.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dbdownload
copying dbdownload/__init__.py -> build/lib/dbdownload
copying dbdownload/dbdownload.py -> build/lib/dbdownload
copying dbdownload/dropbox_content_hasher.py -> build/lib/dbdownload
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/dbdownload
copying build/lib/dbdownload/__init__.py -> build/bdist.linux-armv7l/egg/dbdownload
copying build/lib/dbdownload/dbdownload.py -> build/bdist.linux-armv7l/egg/dbdownload
copying build/lib/dbdownload/dropbox_content_hasher.py -> build/bdist.linux-armv7l/egg/dbdownload
byte-compiling build/bdist.linux-armv7l/egg/dbdownload/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/dbdownload/dbdownload.py to dbdownload.cpython-37.pyc
  File "build/bdist.linux-armv7l/egg/dbdownload/dbdownload.py", line 93
    print "1. Go to: " + auth_url
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("1. Go to: " + auth_url)?

byte-compiling build/bdist.linux-armv7l/egg/dbdownload/dropbox_content_hasher.py to dropbox_content_hasher.cpython-37.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying dbdownload.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying dbdownload.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying dbdownload.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying dbdownload.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying dbdownload.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying dbdownload.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/dbdownload-0.3-py3.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing dbdownload-0.3-py3.7.egg
Copying dbdownload-0.3-py3.7.egg to /usr/local/lib/python3.7/site-packages
Adding dbdownload 0.3 to easy-install.pth file
Installing dbdownload script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/dbdownload-0.3-py3.7.egg
Processing dependencies for dbdownload==0.3
Searching for jsonpickle==1.2
Best match: jsonpickle 1.2
Processing jsonpickle-1.2-py3.7.egg
jsonpickle 1.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/jsonpickle-1.2-py3.7.egg
Searching for dropbox==9.4.0
Best match: dropbox 9.4.0
Processing dropbox-9.4.0-py3.7.egg
dropbox 9.4.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/dropbox-9.4.0-py3.7.egg
Searching for six==1.12.0
Best match: six 1.12.0
Processing six-1.12.0-py3.7.egg
six 1.12.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/six-1.12.0-py3.7.egg
Searching for requests==2.22.0
Best match: requests 2.22.0
Processing requests-2.22.0-py3.7.egg
requests 2.22.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg
Searching for urllib3==1.25.3
Best match: urllib3 1.25.3
Processing urllib3-1.25.3-py3.7.egg
urllib3 1.25.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/urllib3-1.25.3-py3.7.egg
Searching for idna==2.8
Best match: idna 2.8
Processing idna-2.8-py3.7.egg
idna 2.8 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/idna-2.8-py3.7.egg
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Processing chardet-3.0.4-py3.7.egg
chardet 3.0.4 is already the active version in easy-install.pth
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg
Searching for certifi==2019.6.16
Best match: certifi 2019.6.16
Processing certifi-2019.6.16-py3.7.egg
certifi 2019.6.16 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/certifi-2019.6.16-py3.7.egg
Finished processing dependencies for dbdownload==0.3

How can I fix it?

**Comment by coandco** [comment]
DBDownload is written as a Python 2 script, and you're trying to run it with Python 3.  It's possible that it could be converted to run on Python 3, but it would take some elbow grease to do so.

**Comment by luftaquila** [comment]
> DBDownload is written as a Python 2 script, and you're trying to run it with Python 3. It's possible that it could be converted to run on Python 3, but it would take some elbow grease to do so.

Ugh it was a simple problem thanks :D
