### ISSUE TITLE
Run on startup on Raspberry Pi

### ISSUE THREAD

**Issue by m-hertig** [ldx/DBdownload#6]
Hi, thank you for this nice script! It works quite well for me. However, I wanted to run it at system boot, making an entry in /etc/rc.local that looks like this:

    /usr/local/bin/dbdownload -s images -t /home/pi/images -i 5 &

Unfortunately when I boot it won't work, it tells again

    URL: https://www.dropbox.com/1/oauth/authorize?oauth_token=fjlkadf8a7dfjxy
    Please authorize this URL in the browser and then press enter

Although I already did the authentication. I authorized again, but it kept showing up. Do you know how to make this work?

**Comment by ldx** [comment]
Hi @m-hertig,

the problem might be that the daemon can't save the token. Can you check that `~/.dbdownload.cache` exists (or whatever you set via the `-a`/`--cache` option)?

**Comment by m-hertig** [comment]
Thank you! I added '-a ~/.dbdownload.cache' and it works like a charm.
